//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPhotosApi.Api.DTOs
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs", IsReference=true)]
    public partial class FileDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime DateField;
        
        private int IdField;
        
        private string NameField;
        
        private string PathField;
        
        private System.Collections.Generic.List<MyPhotosApi.Api.DTOs.ResponseDtos.PropertyDto> PropertiesField;
        
        private bool TypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<MyPhotosApi.Api.DTOs.ResponseDtos.PropertyDto> Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilterFilesDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs", IsReference=true)]
    public partial class FilterFilesDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int PropertyTypeIdField;
        
        private string PropertyValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyTypeId
        {
            get
            {
                return this.PropertyTypeIdField;
            }
            set
            {
                this.PropertyTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyValue
        {
            get
            {
                return this.PropertyValueField;
            }
            set
            {
                this.PropertyValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyTypeDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs", IsReference=true)]
    public partial class PropertyTypeDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyTypeValuesDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs", IsReference=true)]
    public partial class PropertyTypeValuesDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string NameField;
        
        private System.Collections.Generic.List<string> ValuesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Values
        {
            get
            {
                return this.ValuesField;
            }
            set
            {
                this.ValuesField = value;
            }
        }
    }

    //**** clasa adaugata de mine
    partial class PropertyTypeValuesDto
    {
        public override string ToString()
        {
            return Name;
        }
    }
    //*** 
}
namespace MyPhotosApi.Api.DTOs.ResponseDtos
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PropertyDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs.ResponseDtos", IsReference=true)]
    public partial class PropertyDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private string TypeField;
        
        private string ValueField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
}
namespace MyPhotosApi.Api
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateFileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api", IsReference=true)]
    public partial class CreateFileDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string PathField;
        
        private System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<string>> PropertiesField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Path
        {
            get
            {
                return this.PathField;
            }
            set
            {
                this.PathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, System.Collections.Generic.List<string>> Properties
        {
            get
            {
                return this.PropertiesField;
            }
            set
            {
                this.PropertiesField = value;
            }
        }
    }

    //*** ADDED CLASS BY ME
    partial class CreateFileDto
    {
        public CreateFileDto()
        {
            Properties = new Dictionary<int, List<string>>();
        }
    }
    //***

}
namespace MyPhotosApi.Api.Constants
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.Constants", IsReference=true)]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        private bool SucceededField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Succeeded
        {
            get
            {
                return this.SucceededField;
            }
            set
            {
                this.SucceededField = value;
            }
        }
    }
}
namespace MyPhotosApi.Api.DTOs.RequestDtos
{
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModifyFileDto", Namespace="http://schemas.datacontract.org/2004/07/MyPhotosApi.Api.DTOs.RequestDtos", IsReference=true)]
    public partial class ModifyFileDto : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.Dictionary<int, string> AddedPropertiesInfoField;
        
        private System.Collections.Generic.Dictionary<int, string> DeletedPropertiesInfoField;
        
        private int FileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> AddedPropertiesInfo
        {
            get
            {
                return this.AddedPropertiesInfoField;
            }
            set
            {
                this.AddedPropertiesInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> DeletedPropertiesInfo
        {
            get
            {
                return this.DeletedPropertiesInfoField;
            }
            set
            {
                this.DeletedPropertiesInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileId
        {
            get
            {
                return this.FileIdField;
            }
            set
            {
                this.FileIdField = value;
            }
        }
    }

    //*** class added by me
    partial class ModifyFileDto
    {
        public ModifyFileDto()
        {
            AddedPropertiesInfo = new Dictionary<int, string>();
            DeletedPropertiesInfo = new Dictionary<int, string>();
        }
    }
    //***
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMyPhotosService")]
public interface IMyPhotosService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetAll", ReplyAction="http://tempuri.org/IMediaFileService/GetAllResponse")]
    System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto> GetAll();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetAll", ReplyAction="http://tempuri.org/IMediaFileService/GetAllResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto>> GetAllAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/LoadFile", ReplyAction="http://tempuri.org/IMediaFileService/LoadFileResponse")]
    MyPhotosApi.Api.Constants.Response LoadFile(MyPhotosApi.Api.CreateFileDto createFileDto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/LoadFile", ReplyAction="http://tempuri.org/IMediaFileService/LoadFileResponse")]
    System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> LoadFileAsync(MyPhotosApi.Api.CreateFileDto createFileDto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/ModifyMediaFile", ReplyAction="http://tempuri.org/IMediaFileService/ModifyMediaFileResponse")]
    MyPhotosApi.Api.Constants.Response ModifyMediaFile(MyPhotosApi.Api.DTOs.RequestDtos.ModifyFileDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/ModifyMediaFile", ReplyAction="http://tempuri.org/IMediaFileService/ModifyMediaFileResponse")]
    System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> ModifyMediaFileAsync(MyPhotosApi.Api.DTOs.RequestDtos.ModifyFileDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetDirectoryPhotosVideos", ReplyAction="http://tempuri.org/IMediaFileService/GetDirectoryPhotosVideosResponse")]
    System.Collections.Generic.List<string> GetDirectoryPhotosVideos(string directoryPath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetDirectoryPhotosVideos", ReplyAction="http://tempuri.org/IMediaFileService/GetDirectoryPhotosVideosResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetDirectoryPhotosVideosAsync(string directoryPath);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetFilteredMediaFiles", ReplyAction="http://tempuri.org/IMediaFileService/GetFilteredMediaFilesResponse")]
    System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto> GetFilteredMediaFiles(MyPhotosApi.Api.DTOs.FilterFilesDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/GetFilteredMediaFiles", ReplyAction="http://tempuri.org/IMediaFileService/GetFilteredMediaFilesResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto>> GetFilteredMediaFilesAsync(MyPhotosApi.Api.DTOs.FilterFilesDto dto);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/Delete", ReplyAction="http://tempuri.org/IMediaFileService/DeleteResponse")]
    void Delete(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMediaFileService/Delete", ReplyAction="http://tempuri.org/IMediaFileService/DeleteResponse")]
    System.Threading.Tasks.Task DeleteAsync(int id);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/GetAllPropertiesTypes", ReplyAction="http://tempuri.org/IPropertyTypeService/GetAllPropertiesTypesResponse")]
    System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeDto> GetAllPropertiesTypes();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/GetAllPropertiesTypes", ReplyAction="http://tempuri.org/IPropertyTypeService/GetAllPropertiesTypesResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeDto>> GetAllPropertiesTypesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/GetAllPropertyTypesWithValues", ReplyAction="http://tempuri.org/IPropertyTypeService/GetAllPropertyTypesWithValuesResponse")]
    System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeValuesDto> GetAllPropertyTypesWithValues();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/GetAllPropertyTypesWithValues", ReplyAction="http://tempuri.org/IPropertyTypeService/GetAllPropertyTypesWithValuesResponse")]
    System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeValuesDto>> GetAllPropertyTypesWithValuesAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/AddPropertyType", ReplyAction="http://tempuri.org/IPropertyTypeService/AddPropertyTypeResponse")]
    MyPhotosApi.Api.Constants.Response AddPropertyType(string name);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPropertyTypeService/AddPropertyType", ReplyAction="http://tempuri.org/IPropertyTypeService/AddPropertyTypeResponse")]
    System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> AddPropertyTypeAsync(string name);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMyPhotosServiceChannel : IMyPhotosService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MyPhotosServiceClient : System.ServiceModel.ClientBase<IMyPhotosService>, IMyPhotosService
{
    
    public MyPhotosServiceClient()
    {
    }
    
    public MyPhotosServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MyPhotosServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MyPhotosServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto> GetAll()
    {
        return base.Channel.GetAll();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto>> GetAllAsync()
    {
        return base.Channel.GetAllAsync();
    }
    
    public MyPhotosApi.Api.Constants.Response LoadFile(MyPhotosApi.Api.CreateFileDto createFileDto)
    {
        return base.Channel.LoadFile(createFileDto);
    }
    
    public System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> LoadFileAsync(MyPhotosApi.Api.CreateFileDto createFileDto)
    {
        return base.Channel.LoadFileAsync(createFileDto);
    }
    
    public MyPhotosApi.Api.Constants.Response ModifyMediaFile(MyPhotosApi.Api.DTOs.RequestDtos.ModifyFileDto dto)
    {
        return base.Channel.ModifyMediaFile(dto);
    }
    
    public System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> ModifyMediaFileAsync(MyPhotosApi.Api.DTOs.RequestDtos.ModifyFileDto dto)
    {
        return base.Channel.ModifyMediaFileAsync(dto);
    }
    
    public System.Collections.Generic.List<string> GetDirectoryPhotosVideos(string directoryPath)
    {
        return base.Channel.GetDirectoryPhotosVideos(directoryPath);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetDirectoryPhotosVideosAsync(string directoryPath)
    {
        return base.Channel.GetDirectoryPhotosVideosAsync(directoryPath);
    }
    
    public System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto> GetFilteredMediaFiles(MyPhotosApi.Api.DTOs.FilterFilesDto dto)
    {
        return base.Channel.GetFilteredMediaFiles(dto);
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.FileDto>> GetFilteredMediaFilesAsync(MyPhotosApi.Api.DTOs.FilterFilesDto dto)
    {
        return base.Channel.GetFilteredMediaFilesAsync(dto);
    }
    
    public void Delete(int id)
    {
        base.Channel.Delete(id);
    }
    
    public System.Threading.Tasks.Task DeleteAsync(int id)
    {
        return base.Channel.DeleteAsync(id);
    }
    
    public System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeDto> GetAllPropertiesTypes()
    {
        return base.Channel.GetAllPropertiesTypes();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeDto>> GetAllPropertiesTypesAsync()
    {
        return base.Channel.GetAllPropertiesTypesAsync();
    }
    
    public System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeValuesDto> GetAllPropertyTypesWithValues()
    {
        return base.Channel.GetAllPropertyTypesWithValues();
    }
    
    public System.Threading.Tasks.Task<System.Collections.Generic.List<MyPhotosApi.Api.DTOs.PropertyTypeValuesDto>> GetAllPropertyTypesWithValuesAsync()
    {
        return base.Channel.GetAllPropertyTypesWithValuesAsync();
    }
    
    public MyPhotosApi.Api.Constants.Response AddPropertyType(string name)
    {
        return base.Channel.AddPropertyType(name);
    }
    
    public System.Threading.Tasks.Task<MyPhotosApi.Api.Constants.Response> AddPropertyTypeAsync(string name)
    {
        return base.Channel.AddPropertyTypeAsync(name);
    }
}
